/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indielink_indielink_Audio */

#ifndef _Included_com_indielink_indielink_Audio
#define _Included_com_indielink_indielink_Audio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_indielink_indielink_Audio
 * Method:    audio_analysis
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_indielink_indielink_Audio_audio_1analysis
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
