/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indielink_indielink_Audio_Essentia */

#ifndef _Included_com_indielink_indielink_Audio_Essentia
#define _Included_com_indielink_indielink_Audio_Essentia
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_indielink_indielink_Audio_Essentia
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_indielink_indielink_Audio_Essentia_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
